### ISSUE TITLE
Project proposal

### ISSUE THREAD

**Issue by msarker000** [msarker000/ml-group-project#3]

**Comment by marjanrez** [comment]
[ML_Final_project_proposal.docx](https://github.com/msarker000/ml-group-project/files/4559243/ML_Final_project_proposal.docx)

**Comment by msarker000** [comment]
place this file into documents folder with commit message as 'issue-3:  Project proposal'

**Comment by msarker000** [comment]
i am not seeing ML_Final_project_proposal.docx on documents

here is the steps you should follow
 
copy ML_Final_project_proposal.docx to documents folder in your workspace
then do 
git add ML_Final_project_proposal.docx
git commit -m 'issue-3: Project proposal''
git push origin master

**Comment by marjanrez** [comment]
are you able to see that now?

**Comment by msarker000** [comment]
i did this how i was wanting.  here is how i did

ayub@ayubs-MacBook-Pro documents (master) $ cp ~/Downloads/ML_Final_project_proposal.docx  .
ayub@ayubs-MacBook-Pro documents (master) $ ls
ML_Final_project_proposal.docx	notes.txt
Project Proposal
ayub@ayubs-MacBook-Pro documents (master) $ cd ..
ayub@ayubs-MacBook-Pro ml-group-project (master) $ ls
data			experimental-notebooks	scripts
documents		ml_project.ipynb
ayub@ayubs-MacBook-Pro ml-group-project (master) $ git add documents/ML_Final_project_proposal.docx 
ayub@ayubs-MacBook-Pro ml-group-project (master) $ git commit -m 'issue-3: Project proposal'
[master cefbd32] issue-3: Project proposal
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 documents/ML_Final_project_proposal.docx
ayub@ayubs-MacBook-Pro ml-group-project (master) $ git push -u origin master
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 11.55 KiB | 11.55 MiB/s, done.
Total 4 (delta 0), reused 0 (delta 0)
To https://github.com/msarker000/ml-group-project.git
   a9ab54c..cefbd32  master -> master
Branch master set up to track remote branch master from origin.
ayub@ayubs-MacBook-Pro ml-group-project (master) $

**Comment by msarker000** [comment]
all the documents like final report, any presentation will be in documents folder.

**Comment by msarker000** [comment]
thanks

**Comment by marjanrez** [comment]
all right, thanks
